name: Render Deploy

on:
  push:
    branches:
      - master # Change this to your main branch name or the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger deployment to Render
        run: |
          curl -X POST https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploy \
               -H 'Content-Type: application/json' \
               -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'
